// Client.cpp : main project file.
///////////////////////////////////////////////////////////////////////
// Client.cpp - main project file generated by IDE                   //
// ver 1.0 4/29/2012                                                 //
// Language:    Visual C++, Visual Studio 2010, SP1                  //
// Application: CSE 687 Project4                                     //
// Author:      Junwen Bu                                            //
///////////////////////////////////////////////////////////////////////
/*
 * Module Operations:
 * =================================================
 * This module is generated by Visual Studio 2010.
 * It is the main project file.
 *
 * Required Files:
 * ==========================================
 * Form1.h, CopyDlls.h stdafx.h
 *
 * Function(Interface) Catalog:
 * ==========================================
 * int main(array<System::String ^> ^args) // the main function 
 */

#include "stdafx.h"
#include "Form1.h"
#include "CopyDlls.h"
using namespace Client;

[STAThreadAttribute]
int main(array<System::String ^> ^args)
{
	// Enabling Windows XP visual effects before any controls are created
	Application::EnableVisualStyles();
	Application::SetCompatibleTextRenderingDefault(false); 
	// Create the main window and run it
  Application::Run(gcnew Form1());

	return 0;
}
